### PR TITLE
DEVJIRA-0 Add Docker-Magento

### PR DESCRIPTION
**Pull request by bartboy011**
This PR adds a docker compose setup that allows for local development of the Magento app.

@ActiveCampaign/integration

### CODE REVIEW

**Comment by bartboy011** [comment]
@ActiveCampaign/integration please review

**Comment by mthommes** [comment]
@bartboy011 Very excited about this! Does it allow us to access a local Magento interface as well (to test the extension)?

**Comment by bartboy011** [comment]
@mthommes It does! Rather than needing to upload the extension to a live server, we should (theoretically) be able to do everything locally instead.

**Comment by bartboy011** [comment]
@cristiangrama Per your comments on #3, I'm going to close this PR since all it does is add Dockerized-Magento to the repo.

**Pull request closed without merging**
